### ISSUE TITLE
Speed optimization

### ISSUE THREAD

**Issue by imoscovitz** [imoscovitz/wittgenstein#4]
Opening up a new issue related to speed optimizations for @flamby and anyone else who may be interested.

I ran some diagnostics, and the main culprit seems to be the Cond/Rule.covers functions. They are called a large number of times because they are used to filter the dataframe for assessing each potential action-step, which is pretty rough. ~33% of the pain happens during calls to pandas; the rest is Python.

Some speed-up possibilities:

User-specified training limits:
- I've committed an implementation of `max_rules`, `max_rule_conds`, and `max_total_conds` for both IREP and RIPPER (see https://github.com/imoscovitz/wittgenstein/issues/3 or docstrings). This will permit hard user-specified limits on training complexity. max_rules and `max_total_conds` trigger early-stopping. These parameters can make a big difference in training time.

Algorithmic options:
- There is a memoization optimization I can add to my RIPPER implementation for the k optimization stage to reduce the big-O by a factor a number of rules in the model. Should make a difference for large (even >=15 or so rules) models.
- attribute selection: option to prune from possible conds those values which occur infrequently in pos class examples (potentially destructive, but could be worth it for non-noisy but high-dimensional or high-unique-value datasets)

Data structure changes:
- recasting pd.dtypes as categorical (somehow this seems to be making things worse)
- tokenizing categories as integers in pandas ~5% speedup (somewhat invasive solution)
- replacing pandas with Python set operations by storing Conditions as sets of row indices, and replacing pandas filtering with unions/intersections. Improved big-O (would shrink something like a c conds*n to a (c-1)*log(n)), but also pushes code to Python instead of Pandas. (invasive, higher memory usage, and would make mid-growrule entropy-based binning impossible, but potentially awesome).

Languages:
- reimplementing portions in c++, numpy, or cnumpy with a python wrapper (potentially drastic but potentially faster than pandas, and obviously, in the case of c++, python)

Multithreading:
- The nastiest part seems multithreadable. For example, adding a Cond to a Rule includes a factor of O(all unique values in the dataset) -- and these calls don't depend on one another for parameters.

If anyone has thoughts or wants to advocate for any of these (let's hear it for multithreading, @flamby?), hit that respond button.

-Ilan

**Comment by flamby** [comment]
> * reimplementing portions in c++, numpy, or cnumpy with a python wrapper (potentially drastic but potentially faster than pandas, and obviously, in the case of c++, python)

Maybe [numba](http://numba.pydata.org/) could be of some help. 

> Multithreading:
> 
> * The nastiest part seems multithreadable. For example, adding a Cond to a Rule includes a factor of O(all unique values in the dataset) -- and these calls don't depend on one another for parameters.

Have you considered using [Dask](https://github.com/dask/dask)? 
I use it when I have pandas bottlenecks, or when I need to scale-out GridSearch on several machines. It might be easier to implement than dealing w/ threads.

**Comment by imoscovitz** [comment]
Thanks, these are great suggestions!

Here's a preliminary update.

- I've been playing around with numba -- it's been a little tricky to jitclass some parts, but making a some progress

Promising news on the algorithm/data structure front:
- Created a pandas wrapper called CatNap (categorical number map) that sped up the function that's consuming ~80% of training time by something like ~100x. On grow_rule -- which is the combinatorically expensive higher-level function -- there's a ~40x speed improvement 
- It takes advantage of the fact that you know features are categorical: you fit a CatMap on a df, and it maps {Cond: set(indices)}. So you can do set computation on pandas indices without having to search the df's values
- In addition, replacing dfs with sets could also make it much simpler to numba low-level functions. If you have numba experience, might be good to ask you to take a peek at parts of the code once I've woven in some numba to see if you see potential numba optimizations
- Still refactoring -- much of the way through .base,  probably also need to refactor irep and ripper -- might be the next update after proba (0.1.7)

Thanks!
-Ilan

**Comment by flamby** [comment]
Hi @imoscovitz 

> * I've been playing around with numba -- it's been a little tricky to jitclass some parts, but making a some progress

Unfortunately, I've no low-level (C, C++, etc.) skills at all. I once used numba jit decorator, but that my all experience with it ;-)

> * Created a pandas wrapper called CatNap (categorical number map) that sped up the function that's consuming ~80% of training time by something like ~100x. On grow_rule -- which is the combinatorically expensive higher-level function -- there's a ~40x speed improvement

That's fantastic, why bother w/ numba then? a such improvement will be good enough for sure, don't you think.

thanks!

**Comment by imoscovitz** [comment]
Exciting times! Made the first major speed optimization commit: refactored the package and algorithms so they can use CatNap optimization. I'm seeing a decent speedup from it. 

Sidenotes:
- For now, you can toggle on/off the speed optimization in .fit with the cn_optimize param (default is True).
- For now, random_state when optimize is on might not match up with the random_state of off.

Here's how the changes should affect the main time-sucks:
- IREP/RIPPER grow ruleset (should be much faster)
- RIPPER optimization stage (maybe some improvement?)
- binning (unchanged)

Curious to hear how this first speed optimization works out for you. In addition to ```%timeit```, you can set ```irep.fit(... verbosity>=2)``` or
```
%load_ext line_profiler
%prun irep.fit(...) 
```
to see where it's taking the most time for your problem.

Thanks!
Ilan

**Comment by flamby** [comment]
Hi @imoscovitz 

> Exciting times! Made the first major speed optimization commit: refactored the package and algorithms so they can use CatNap optimization. I'm seeing a decent speedup from it.

Indeed. It's huge. Here are my results w/ a small dataset ; shape : (3362, 8):

| Algo | `cn_optimize=True` | `cn_optimize=False` |
| --- | --- | --- |
| IREP | 0.7 second | 11.58 seconds |
| RIPPER k=0 | 37 seconds | 117 seconds |
| RIPPER k=2 | 5350 seconds | _had to stop, took too long_ |

> * IREP/RIPPER grow ruleset (should be much faster)
> * RIPPER optimization stage (maybe some improvement?)
As you see, it's huge for IREP and RIPPER if k=0, whereas k=2 performance is almost unchanged.

So except for RIPPER default optimization, the boost is more or less one order of magnitude.

Kudos!

I noted that this commit broke the `fit` usage w/ _df_ and _y_ (i.e. w/o `class_feat`)

**Comment by imoscovitz** [comment]
Hi @flamby,

Hooray! Thanks!

> I noted that this commit broke the fit usage w/ df and y (i.e. w/o class_feat)

- Should be fixed now.

> As you see, it's huge for IREP and RIPPER if k=0, whereas k=2 performance is almost unchanged.

- I think it could be worth going after RIPPER speedups, how about you? Began drawing up a memoization strategy for improving the time complexity of k optimization. It might help a little with the non-k part too.

**Comment by imoscovitz** [comment]
More good news. I found opportunities to extend the catnap speed optimization deeper into RIPPER's k optimization stages. The latest commit has substantial speed improvements for that part too. 

@flamby, want to let me know how it works out for you?
Thanks!
-Ilan

**Comment by imoscovitz** [comment]
Just got 3 orders of magnitude improvement on a test of RIPPERk=2 on a subset of the census dataset and nearly 4 orders on the congress dataset...yikes

**Comment by flamby** [comment]
Hi @imoscovitz 

> More good news. I found opportunities to extend the catnap speed optimization deeper into RIPPER's k optimization stages. The latest commit has substantial speed improvements for that part too.

Impressive improvement 👍
_Fitted on 972 features, shape=(2913, 972) :_

| Run | Time | Precision | Best precision | Recall |
| --- | --- | --- | --- | --- |
| RIPPER k=0 | 572 sec | 0.65 | 0.72 | 0.67 |
| RIPPER k=1 | 609 sec | 0.65 | 0.72 | 0.67 |
| RIPPER k=2 | 643 sec | 0.65 | 0.72 | 0.67 |
| IREP | 590 sec | 0.64 | 0.75 | 0.57 |

So now RIPPER is as fast as IREP.
Regarding the score, i think it's just that my data is not responsive to RIPPER optimization. I even tried on a smaller dataset k=50, an in the end,  the very same score than k=0 ;-)

I think speed optimization is a done task for a while ;-)

Kudos!

**Comment by imoscovitz** [comment]
Thanks, @flamby. The latest commit fixes that. .fit also now supports inputting training data in numpy or python iterable types. Hopefully that makes your pipelining a little easier -- let me know how it works out for you!

Thanks!
Ilan

**Comment by flamby** [comment]
Hi @imoscovitz 

Thanks a lot. I've tried it, it works for training (`fit`) but not for inference (`predict` or `predict_proba`) for which I get this error
```
/lib/python3.7/site-packages/wittgenstein/irep.py in predict_proba(self, X_df, give_reasons, ret_n, min_samples, discretize)
    174     def predict_proba(self, X_df, give_reasons=False, ret_n=False, min_samples=1, discretize=True):
    175         # Drop class feature if user forgot to:
--> 176         df = X_df if self.class_feat not in X_df.columns else X_df.drop(self.class_feat, axis=1)
    177         return self.ruleset_.predict_proba(df, give_reasons=give_reasons, ret_n=ret_n, min_samples=min_samples, discretize=True, bin_transformer=self.bin_transformer_)
    178 

AttributeError: 'numpy.ndarray' object has no attribute 'columns' 
```

I was busy the last days, but I'll have time to move on several fronts w/ your lib in the coming days :-)

**Comment by imoscovitz** [comment]
Closing this. We might include speed optimizations in the future, but for now we're happy with the major speedup cn_optimize provides.
